### ISSUE TITLE
Error in (function (cl, name, valueClass) :    ‘version’ is not a slot in the class definition for “lavaan.mi”

### ISSUE THREAD

**Issue by Ning-pku** [TDJorgensen/lavaan.mi#4]
Error in (function (cl, name, valueClass) : 
  ‘version’ is not a slot in the class definition for “lavaan.mi”

when I run "out2<- lavaan.mi::sem.mi(model2, data=imp, std.lv=T, verbose=T)", I always encounter this error, even though I have confirmed that my versions of lavaan and lavaan.mi are aligned with the requirements.
> packageVersion("lavaan")
[1] ‘0.6.17’
> packageVersion("lavaan.mi")
[1] ‘0.1.0.25’

How could I resolve this issue? Thanks very much!

**Comment by TDJorgensen** [comment]
`lavaan.mi` requires the latest development version of `lavaan`:

```
remotes::install_github("yrosseel/lavaan")
```
