### ISSUE TITLE
Error in `summary()` and `parameterEstimates.mi()`: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by simongrund1** [TDJorgensen/lavaan.mi#5]
I recently used `lavaan.mi` for a growth model and received an error message when running the `summary()` command on the `lavaan.mi`-class object. The error seems to occur in `parameterEstimates.mi()`, where the "if" statement that checks for large degrees of freedom when creating text output does not exclude non-free parameters.

Error message:
Error in if (zstat && output == "text" && any(PE$df > 999.5)) { : missing value where TRUE/FALSE needed

Changing the "if" statement to exclude non-free parameters (`PE$df[free] > 999.5`) seems to solve the issue. 

**Reproducible example**

```
library(MASS)
library(mice)
library(lavaan.mi)

# simulate data
set.seed(4954)
n <- 100
nT <- 3

eta <- MASS::mvrnorm(n = n, mu = c(1, 0.5), Sigma = diag(c(1, .20)))
eps <- MASS::mvrnorm(n = n, mu = rep(0, nT), Sigma = diag(1, nT))
lambda <- cbind(1, seq.int(0, nT-1))

y <- t(lambda %*% t(eta)) + eps
colnames(y) <- paste0("y", 1:nT)

y1 <- y
y1[runif(n*nT) < .20] <- NA
dat <- as.data.frame(y1)

# run MI
imp <- mice::mice(data = dat, m = 5, maxit = 5)
implist <- mice::complete(imp, "all")

# analyze
mod <- "
i=~1*y1+1*y2+1*y3
s=~0*y1+1*y2+2*y3
"

fit <- growth.mi(model = mod, data = implist)

summary(fit)                                       # error
parameterEstimates.mi(fit, output = "text")        # error
parameterEstimates.mi(fit, output = "data.frame")  # no error
```

**Comment by TDJorgensen** [comment]
Thanks for the reprex @simongrund1 and the fix @uhkeller!
